/**
 * Human-readable animation titles by object ID.
 */
export const AnimationTitles = Object.freeze({
    500: "Bank Closed for Remodeling",
    501: "Counting Visitors",
    502: "Laughing All the Way to the Bank",
    505: "The Light's About to Change",
    508: "Welcome to Nubby's",
    509: "Red Car vs. Blue Car",
    510: "Build a Dune Buggy",
    511: "Why Don't We Have Elbows?",
    512: "Why Don't More of Us Ride Bicycles?",
    513: "Snappy Automobile",
    514: "Beautiful Day",
    515: "Lost My Memory",
    517: "Be Quiet, It's a Hospital",
    519: "Your Head's a Little Loose",
    520: "Late for Plastic Surgery",
    521: "I Can't Place the Name",
    525: "Can't Spell Pepper",
    526: "Build Schools, Not Prisons",
    527: "The Condiment Family",
    528: "Laura Can't Add",
    529: "Nothing Adds Up",
    530: "What Comes After Two?",
    531: "Chip Off the Old Block",
    532: "The Man With No Nose",
    533: "I'm Innocent!",
    534: "Papa's Shoes Are Untied",
    535: "Now That's Art",
    536: "Good Dancers",
    537: "How Many Claws?",
    538: "Play Me a Jailbreak Tune",
    539: "It's Me, the Tree",
    540: "Let Me Out",
    541: "Breaking and Entering",
    542: "I Demand a Mistrial",
    543: "Build a Jet Ski",
    544: "Throw Me to the Refreshment Stand",
    545: "It's Hot",
    546: "Perfect for Motos",
    547: "Even the Sharks Come Here",
    548: "Last One In Is a Dirty Brick",
    549: "Stoked and Ready to Smoke",
    550: "That Was Fast",
    552: "Pull Up to the Buoy",
    553: "Twisted Course on the North Side",
    554: "Shark Spotting a Dog",
    555: "Keep the Buoys to Your Right",
    556: "Heads Up, Glue Your Bow",
    557: "Reminds Me of Me",
    560: "Hi There!",
    561: "My Bricks Are Killing Me",
    563: "Build a Helicopter!",
    564: "All's Quiet on This Side",
    565: "Not Very Quiet at All",
    566: "Move It, Booking",
    567: "Best Pizza on the Island",
    568: "Mozart of Meatballs",
    569: "Faster Than a Loose Brick on Ice",
    570: "Where Is My Piano?",
    571: "Learn to Read, Not Skateboard",
    572: "Too Cool for Words",
    573: "Unusual Bricks Out There",
    574: "P-I-Z-Z-A",
    575: "Watch Me Dance",
    576: "Sir Circumference",
    577: "You Look Thin, Officer Nick",
    578: "I'll Smell for You",
    579: "Looking Snappy",
    580: "Let's Dance, Officer Nick",
    581: "I Remember the White Apron",
    582: "Picasso of Pizza",
    583: "Music Makes the Flowers Sing",
    584: "Tickle the Ivories",
    585: "Songs Fill My Bricks With Joy",
    586: "That's My Pepper",
    587: "Your Smile Reminds Me of a Song",
    588: "You Look So Lovely I Could Dance",
    589: "Good Friend Song",
    590: "We Adore a Lola",
    591: "Come Dance With Me",
    592: "That Pizza Smells So Good",
    593: "Concert of a Kitchen",
    594: "Pizza Symphony",
    595: "Dance With the Pizza",
    596: "You're Seeing Someone Else",
    597: "Biggest Slice, No Elbows",
    598: "Sauce on the Dough",
    599: "Pizza Masterpiece",
    603: "Click on the Pizzeria",
    604: "Gorilla Flip",
    605: "Bad Smeller",
    606: "Airborne!",
    607: "Mama Wrote Me a Theme Song",
    608: "Pizza Delivery Dude",
    610: "Something's Not Put Together Right",
    611: "Use Your Brain",
    612: "Build a Race Car",
    613: "Race to the Pit Stop",
    614: "You're Lost",
    615: "Ask for Directions",
    616: "Going in Circles",
    617: "50 Is Legal",
    618: "I Grind That Fast",
    619: "Go! Go! Go!",
    620: "Goal!",
    621: "Store Closed for Remodeling",
    622: "Shark Warning",
    623: "Things Can Change",
    624: "Don't Cut Corners",
    625: "I Remember Everything",
    626: "Go Low and Slow",
    627: "You Can Count on Me",
    628: "Very Police-Like",
    629: "Lost Count on Patrol",
    630: "Parrot Stuck in a Car Again",
    631: "Register Those Songs",
    632: "Drive as Well as You Play Piano",
    633: "An Anthem for Lego Island",
    634: "I Ought to Get Me One of Those",
    635: "Humming Your Tune",
    636: "Faster Than a Car",
    637: "Make the Birds and Trees Sing",
    638: "I Can Count on You",
    639: "504 Pizzas a Week",
    640: "Are You Going to Sing?",
    641: "If I Wasn't on Duty",
    642: "They Look Like They Smell Delicious",
    643: "Papa, You're the Greatest",
    644: "Twisted a Brick Dancing",
    645: "Slow Down Your Dance Steps",
    646: "You Move Way Too Fast",
    647: "Snapping Pepper Together",
    648: "Lucky to Have You, Sis",
    649: "Cessquapavillion",
    650: "Sir Comference, Knight",
    651: "Papa Can't Sing",
    652: "Consider This a Warning",
    653: "Crime Doesn't Pay",
    654: "Don't Block the Road",
    655: "Just a Matter of Time",
    656: "Don't Run Into Anybody",
    657: "Try the Helicopter",
    658: "One Pretty Island",
    660: "You Must Have My Mail",
    661: "My Parrot Got Loose",
    662: "Rain, Snow, Sleet, and Hail",
    663: "Rad Race Car With a Skull Decal",
    664: "Lovely Day for a Bike Ride",
    665: "Perfect Day for Gardening",
    666: "Cool Hat",
    667: "Check Out the Tunes",
    668: "Protect and Serve",
    669: "You Look Lost",
    670: "Eyes Straight Ahead",
    671: "Brickster's Locked Behind Closed Doors",
    672: "A Lovely Day to You",
    673: "Save It for the Racetrack",
    674: "A Gracious Howdy Do",
    676: "My Goodness Gracious!",
    677: "Hey, What's Up!",
    680: "Race Begins at the Buoy",
    681: "Ain't She a Beaut!",
    682: "Let's See What It Can Do",
    683: "The Helicopter Maniac",
    684: "A Regular Studs Lincoln",
    685: "You Show Real Potential",
    686: "Thanks for Your Help",
    688: "Parrot Dive-Bombing",
    689: "Look Out!",
    690: "I'm Already Here!",
    691: "Look Before You Leap!",
    692: "Stand Up, Sit Down, Fight!",
    697: "Won't Somebody Help That Poor Man?",
    712: "Pizza So Hot",
    713: "Still Warm",
    714: "Cold Pizza",
    716: "Must Be Pizza Day",
    717: "Fat as a Brick House",
    718: "Extreme Skateboard Experience (Papa)",
    719: "Don't Be Afraid to Go Vert (Papa)",
    720: "You Go, We'll Think of Something",
    721: "Extreme Skateboard Experience (Pepper)",
    722: "Don't Be Afraid to Go Vert (Pepper)",
    723: "You're Looking Fat, Mama",
    724: "Nix Polizoria #1",
    725: "Nix Polizoria #2",
    726: "Nix Polizoria #3",
    727: "Deliver Pizza to Nubby",
    730: "Take Pepper's Skateboard",
    731: "Pepper Should Be Back Soon",
    732: "Rush Order for Studs Lincoln",
    733: "Sad Pizza Song",
    734: "Another One for the Track",
    735: "Skateboarding Is Like Dancing",
    736: "Pizza's Still on the Ceiling",
    737: "Maybe Pepper Will Come Back",
    738: "Just Don't Fall!",
    739: "Lucky Pizza",
    740: "Reheat It on the Engine",
    741: "Cold Pizza in Reverse",
    743: "Pizza's Still Warm, Quick Operating!",
    744: "Pizza's DOA!",
    745: "Laura, Deliver to the Hospital",
    746: "Hospital Needs Another Pizza",
    747: "One More Pizza to Go",
    748: "Grind It or Smith It? (Mama)",
    749: "Twice as Much Topping",
    750: "Figuring Something Out",
    751: "Grind It or Smith It? (Pepper)",
    752: "A True Betty Now",
    753: "Rip It Up!",
    755: "Bring the Pizza Over Here",
    756: "Helicopters Are Fun",
    757: "Pepperoni Again?!",
    758: "Build That Helicopter",
    759: "Wrong Pizza",
    760: "Papa's Famous Garlic Pizza",
    761: "Send Pizza to the Jail (Mama)",
    762: "Send Pizza to the Jail (Papa)",
    764: "Party at the County Jail",
    766: "Something About That Call",
    767: "Back Already?",
    768: "First Tow's on Me",
    769: "Oil in Your Blood, Mama",
    770: "Good Reflexes, Nick",
    771: "Let Me Throw Pizzas",
    772: "You're the Best, Laura!",
    773: "Heard You Had Trouble",
    774: "By the Time You Can Drive",
    775: "Practice Makes Perfect",
    776: "Not a High-Speed Chase Vehicle",
    777: "I'm Not Blaming You, Papa",
    778: "Come Back and Do Better",
    779: "Thanks for Helping!",
    780: "That Took a Long Time!",
    781: "Smashing So Much Stuff",
    782: "Nancy Prefers I Don't Sing",
    783: "Good Thing You Don't Catch Crooks That Way",
    784: "He Who Does Something",
    785: "A Little More Practice, Laura",
    786: "Try Again Sometime!",
    788: "I've Got to Finish the Race!",
    789: "Red Car Is Blocking the Track!",
    790: "Didn't You See the Red Car?",
    791: "Nothing to See Here",
    792: "I Said We'd Be Back!",
    856: "I Love Jet Skis!",
    857: "Move Your Hand Off the Wheel",
    858: "I Love Two Wheelers!",
    859: "Have a Gas on That Skateboard!",
    860: "Jet Ski First Place!",
    861: "Jet Ski Second Place!",
    862: "Jet Ski Third Place",
    863: "Jet Ski Better Luck Next Time",
    864: "Race First Place!",
    865: "Race Second Place!",
    866: "Race Third Place!",
    867: "Race Better Luck Next Time",
    868: "Start Your Engines!",
});
